version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME} # Replace with your DB name
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Replace with your password
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  java-app:
    build: .
    ports:
      - "${APP_PORT}:8083"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      # Use 'mysqldb' as the hostname because Docker links them by service name
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}