version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: JWTPractice # Replace with your DB name
      MYSQL_ROOT_PASSWORD: MySql!3306 # Replace with your password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  java-app:
    build: .
    ports:
      - "8080:8083"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      # Use 'mysqldb' as the hostname because Docker links them by service name
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/JWTPractice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MySql!3306